# Generated by Django 5.0.3 on 2024-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='useremail',
            field=models.EmailField(max_length=255),
        ),
    ]
